# Generated by Django 3.2.3 on 2021-05-20 15:42

import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='noticias/tanque_arma3.jpg', storage=api.utils.OverwriteStorage(), upload_to='misiones')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mision', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
