# Generated by Django 3.2.3 on 2021-06-16 20:20

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgMision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=api.utils.OverwriteStorage(), upload_to='misiones')),
                ('mision', models.ManyToManyField(related_name='mision_img', to='api.Mision')),
            ],
        ),
    ]
