# Generated by Django 3.2.3 on 2021-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mision'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
