# Generated by Django 3.2.3 on 2021-06-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_misionimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionimg',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
