# Generated by Django 3.2.3 on 2021-06-16 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_misionimg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionimg',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='misionimg',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mision_img', to=settings.AUTH_USER_MODEL),
        ),
    ]
